development:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: f2d40c8db4c13e7dc594591a8cd4eb6524685c1b820c59ac6cb26dfd28b23ea0ef21eeebc8b21076e172f5c3438130cce6c075bcd9af5091c0dd7659bb9f5028

test:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: 0288012b3cdd0ef961e2843c6f629643b2176208facc196171897a2c0bcc3e2ee9b39c30c264fa6b91cf8f2671a185652345ddb3d2a2e09178cc393003db0da8

production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
